In [1]:
import pandas as pd

Загрузим табличку с нашими данными про длительность поездок такси! 

ссылка на <a href='https://yadi.sk/d/guhN1YgFKT41qQ'>датасет</a>

In [19]:
df = pd.read_csv('taxi_dataset_with_target.csv', index_col=0)

df.head()

vendor_id      pickup_datetime  passenger_count  \
id                                                           
id2875421          1  2016-03-14 17:24:55       930.399753   
id2377394          0  2016-06-12 00:43:35       930.399753   
id3858529          1  2016-01-19 11:35:24       930.399753   
id3504673          1  2016-04-06 19:32:31       930.399753   
id2181028          1  2016-03-26 13:30:55       930.399753   

           store_and_fwd_flag  trip_duration  distance_km  
id                                                         
id2875421                   0          455.0     1.500479  
id2377394                   0          663.0     1.807119  
id3858529                   0         2124.0     6.392080  
id3504673                   0          429.0     1.487155  
id2181028                   0          435.0     1.189925

In [26]:
x_train = df.drop(['pickup_datetime','trip_duration'],axis=1)
y_train = df['trip_duration']

Попробуем построить модель Линейной Регрессии!

В качестве Выборки используйте таргетную колонку (*trip_duration*) и все признаки, кроме времени начала заказа (*pickup_datetime*)

Для начала воспользуемся "коробочным решением". Для этого создайте переменную model, положите в нее класс **LinearRegression** из модуля **linear_model** библиотеки **sklearn**.

Далее воспользуйтесь методом **fit**, положите в него через запятую: массив **X**, состоящий из признаков объектов (можно pandas dataframe'ом, а можно numpy-массивом), и массив **Y** с таргетами.

In [4]:
from sklearn.linear_model import LinearRegression

### Your code is here

In [5]:
model=LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [9]:
import numpy as np

Чтобы посмотреть на значения полученных коэффициентов модели, следует обратиться к атрибуту **coef_** класса линейной регрессии. Для просмотра свободного веса, к атрибуту **intercept_** 

In [11]:
np.round(model.coef_, 3) , np.round(model.intercept_,3)


(array([198.463,   0.296,  56.469, 115.274]), 171.657)

In [ ]:
198.463, 0.296, 56.469, 115.274, 171.657

In [1]:
### Полученные коэффициенты будут являться ответом на задание 5 в ЛМС.
### Перечислите коэффициенты через запятую и пробел, округлив до 3 знаков после точки.
### Используйте точку в качестве десятичного разделителя.

Теперь реализуйте функцию LinearRegressionByMatrix, которая будет принимать на вход 3 параметра:

Матрицу объект-признак **(X)**, вектор с ответами **(Y)**, булевый параметр **fit_intercept**, цель которого - добавить константный признак (состоящий из единичек), если True, и ничего не делать, если False.

Функция должна вернуть одномерный np.array объект с оцененными **$\beta_1, ..., \beta_n, \beta_0$**

Реализуйте решение через аналитическое решение в матрицах из лекции и практики:

$$
\beta^* = (X^T \cdot X)^{-1} \cdot X^T \cdot Y
$$

In [39]:
import numpy as np

### Your code is here

def LinearRegressionByMatrix(X: np.array, Y: np.array, fit_intercept: bool = True):
        """
        :param X: матрица объектов
        :param Y: вектор (матрица с 1 столбцом) ответов
        :param fit_intercept: добавить ли константную переменную в данные?
        
        :return: одномерный numpy-array с полученными коэффициентами beta
        """
        
        if fit_intercept:
            X = np.hstack((X,np.ones((np.array(X).shape[0], 1))))
        x_t = np.dot(X.T, X)
        x_t_inv = np.linalg.inv(x_t)
        x_t_inv_x_t = np.dot(x_t_inv, X.T)
              
        
        return np.dot(x_t_inv_x_t, Y)

In [13]:
X_train = df.drop(['trip_duration', 'pickup_datetime'], axis=1).values
Y_train = df['trip_duration'].values

# LinearRegressionByMatrix(X_train, Y_train)

In [44]:
my_result = LinearRegressionByMatrix(X_train, Y_train)

In [5]:
### Полученные коэффициенты будут являться ответом на задание 6 в ЛМС.
### Перечислите коэффициенты через запятую и пробел, округлив до 3 знаков после точки.
### Используйте точку в качестве десятичного разделителя.

Получились ли коэффициенты такими же, как и в "коробочном" варианте?

Имея коэффициенты модели, можно восстановить предсказания для каждого объекта!

Сделайте это через операцию матричного произведения матрицы **X** и полученных коэффициентов (как результат работы *LinearRegressionByMatrix*)

In [46]:
np.dot(X_train, my_result[:-1])

array([ 647.11814674,  484.00254122, 1210.99033395, ..., 1377.08476208,
        401.77409035,  406.57722534])

In [48]:
np.hstack(())

array([[  1.        , 930.39975328,   0.        ,   1.50047895],
       [  0.        , 930.39975328,   0.        ,   1.80711941],
       [  1.        , 930.39975328,   0.        ,   6.39208025],
       ...,
       [  1.        , 930.39975328,   0.        ,   7.83295239],
       [  0.        , 930.39975328,   0.        ,   1.09378613],
       [  0.        , 930.39975328,   0.        ,   1.13545341]])